# Exploration des données

In [2]:
# Importation des libraries nécessaires
import pandas as pd
# import statistics as stats

## 1. Base hvstat_africa_data_v1.0.csv

In [3]:
# importation de la base de données
df = pd.read_csv('./data/hvstat_africa_data_v1.0.csv', index_col=0)

df.head()

,country,country_code,admin_1,admin_2,product,season_name,planting_year,planting_month,harvest_year,harvest_month,crop_production_system,qc_flag,area,production,yield
fnid,,,,,,,,,,,,,,,
AO2008A101,Angola,AO,Bengo,none,Banana,Main,2007,10,2008,4,All (PS),0,1364.0,19588.0,14.360704
AO2008A101,Angola,AO,Bengo,none,Banana,Main,2008,10,2009,4,All (PS),0,1364.0,20461.0,15.000733
AO2008A101,Angola,AO,Bengo,none,Banana,Main,2014,10,2015,4,All (PS),0,8706.0,222044.0,25.504709
AO2008A101,Angola,AO,Bengo,none,Banana,Main,2015,10,2016,4,All (PS),0,8706.0,222044.0,25.504709
AO2008A101,Angola,AO,Bengo,none,Banana,Main,2016,10,2017,4,All (PS),0,9549.7,233967.0,24.499932

In [41]:
# taille de la base de données
df.shape

(203125, 15)

In [42]:
# type de données
df.dtypes

country                       str
country_code                  str
admin_1                       str
admin_2                       str
product                       str
season_name                   str
planting_year               int64
planting_month              int64
harvest_year                int64
harvest_month               int64
crop_production_system        str
qc_flag                     int64
area                      float64
production                float64
yield                     float64
dtype: object

In [43]:
# Information sur le DataFrame
df.info()

<class 'pandas.DataFrame'>
Index: 203125 entries, AO2008A101 to ZW2018A118
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   country                 203125 non-null  str
 1   country_code            203125 non-null  str
 2   admin_1                 203125 non-null  str
 3   admin_2                 203125 non-null  str
 4   product                 203125 non-null  str
 5   season_name             203125 non-null  str
 6   planting_year           203125 non-null  int64
 7   planting_month          203125 non-null  int64
 8   harvest_year            203125 non-null  int64
 9   harvest_month           203125 non-null  int64
 10  crop_production_system  203125 non-null  str
 11  qc_flag                 203125 non-null  int64
 12  area                    190428 non-null  float64
 13  production              198346 non-null  float64
 14  yield                   185430 non-null  float64
dtypes: float64(3), int64(5), str(7)
memory usage: 24.8+ MB

In [44]:
# résumé des données quantitatives
df.describe()

,planting_year,planting_month,harvest_year,harvest_month,qc_flag,area,production,yield
count,203125.000000,203125.000000,203125.000000,203125.000000,203125.000000,1.904280e+05,1.983460e+05,185430.000000
mean,2005.638257,6.007074,2005.968039,8.452736,0.027490,3.282292e+04,4.014160e+04,3.632818
std,10.613502,3.118320,10.664340,3.615595,0.226541,4.091427e+06,2.086109e+05,12.292582
min,1960.000000,1.000000,1960.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000047
25%,2000.000000,3.000000,2000.000000,5.000000,0.000000,2.000000e+02,2.746701e+02,0.541429
50%,2007.000000,6.000000,2008.000000,10.000000,0.000000,1.855000e+03,2.248000e+03,0.985439
75%,2014.000000,9.000000,2014.000000,12.000000,0.000000,1.207900e+04,1.552912e+04,2.700000
max,2024.000000,11.000000,2024.000000,12.000000,2.000000,1.751414e+09,8.899134e+06,1229.428571

In [45]:
# résumé des données catégorielles
df.describe(include=["str"])

,country,country_code,admin_1,admin_2,product,season_name,crop_production_system
count,203125,203125,203125,203125,203125,203125,203125
unique,33,33,417,707,94,33,27
top,Benin,BJ,Southern,none,Maize,Main,All (PS)
freq,26770,26770,9055,66748,24313,88059,82950

In [46]:
# nombre de valeurs manquantes par colonne
df.isnull().sum()

country                       0
country_code                  0
admin_1                       0
admin_2                       0
product                       0
season_name                   0
planting_year                 0
planting_month                0
harvest_year                  0
harvest_month                 0
crop_production_system        0
qc_flag                       0
area                      12697
production                 4779
yield                     17695
dtype: int64

In [58]:
# nombre de valeurs manquantes par colonne en pourcentage
round((df.isnull().sum() / len(df)) * 100, 2)

country                   0.00
country_code              0.00
admin_1                   0.00
admin_2                   0.00
product                   0.00
season_name               0.00
planting_year             0.00
planting_month            0.00
harvest_year              0.00
harvest_month             0.00
crop_production_system    0.00
qc_flag                   0.00
area                      6.25
production                2.35
yield                     8.71
dtype: float64

In [ ]:
# nombre de valeurs manquantes global
df.isnull().sum().sum()

np.int64(35171)

In [59]:
# nombre de valeurs manquantes global en pourcentage
round((df.isnull().sum().sum() / len(df)) * 100, 2)

np.float64(17.31)

In [ ]:
def clean_data(df):
    # Filter rows based on column: 'production'
    df = df[df['production'].isna()]
    return df

df_clean = clean_data(df.copy())
df_clean.head()

In [ ]:
# Liste des pays uniques dans la colonne "country"
df_clean['country'].unique()

- Nombre de colonnes : 16
- Colonne identifiant : fnid
- Colonnes de type catégorielle : 7
- Colonnes de type numérique : 8
- Nombre de ligne : 203 125
- Période : 1960-2024 (données annuelles)
- Total de valeurs manquantes : 35 171
  - Colonnes concernées : area (12 697), production (4 779), yield (17 695)

Pour **area** et **yield**, nous allons garder les valeurs manquantes en appliquant le principe statisitique de traitement des données. Nous allons donner à ces valeurs la valeur **-99**. Nous allons garder ceux de production également avec **-99**

In [64]:
# Remplissage des valeurs manquantes dans les colonnes "production", "area", "yield" avec -99
df = df.fillna({'area': -99, 'production': -99, 'yield': -99})

## 2. Base meteo_afrique_ouest_2010_2022.csv

In [63]:
# importation de la base de données
df2 = pd.read_csv('./data/meteo_afrique_ouest_2010_2022.csv')

df2.head()

,ville,pays,latitude,longitude,date,precipitation_mm,temp_max_c,temp_min_c,humidite_max_pct,humidite_min_pct,vent_max_kmh
0,Thiès,Sénégal,14.79,-16.93,2010-01-01,0.0,36.2,19.0,60,11,13.2
1,Thiès,Sénégal,14.79,-16.93,2010-01-02,0.0,36.7,15.3,90,10,10.2
2,Thiès,Sénégal,14.79,-16.93,2010-01-03,0.0,35.9,18.3,65,7,15.7
3,Thiès,Sénégal,14.79,-16.93,2010-01-04,0.0,32.9,21.2,56,10,17.6
4,Thiès,Sénégal,14.79,-16.93,2010-01-05,0.0,32.7,18.9,63,10,17.9

In [49]:
# taille de la base de données
df2.shape

(28488, 11)

In [50]:
# type de données
df2.dtypes

ville                   str
pays                    str
latitude            float64
longitude           float64
date                    str
precipitation_mm    float64
temp_max_c          float64
temp_min_c          float64
humidite_max_pct      int64
humidite_min_pct      int64
vent_max_kmh        float64
dtype: object

In [51]:
# conversion de la colonne "date" en type datetime
df2['date'] = pd.to_datetime(df2['date'], format='%Y-%m-%d', errors='coerce')

In [52]:
# Information sur le DataFrame
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 28488 entries, 0 to 28487
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ville             28488 non-null  str
 1   pays              28488 non-null  str
 2   latitude          28488 non-null  float64
 3   longitude         28488 non-null  float64
 4   date              28488 non-null  datetime64[us]
 5   precipitation_mm  28488 non-null  float64
 6   temp_max_c        28488 non-null  float64
 7   temp_min_c        28488 non-null  float64
 8   humidite_max_pct  28488 non-null  int64
 9   humidite_min_pct  28488 non-null  int64
 10  vent_max_kmh      28488 non-null  float64
dtypes: datetime64[us](1), float64(6), int64(2), str(2)
memory usage: 2.4 MB

In [53]:
# description des données quantitatives
df2.describe()

,latitude,longitude,date,precipitation_mm,temp_max_c,temp_min_c,humidite_max_pct,humidite_min_pct,vent_max_kmh
count,28488.000000,28488.000000,28488,28488.000000,28488.000000,28488.000000,28488.000000,28488.000000,28488.000000
mean,12.963333,-12.151667,2016-07-01 12:00:00,2.046493,33.819503,22.379125,71.387391,35.223884,15.731448
min,11.180000,-16.930000,2010-01-01 00:00:00,0.000000,22.500000,12.300000,6.000000,3.000000,4.500000
25%,11.320000,-16.270000,2013-04-01 18:00:00,0.000000,31.200000,20.500000,50.000000,15.000000,12.800000
50%,13.170000,-14.870000,2016-07-01 12:00:00,0.000000,33.700000,22.700000,82.000000,30.000000,15.500000
75%,14.150000,-5.670000,2019-10-01 06:00:00,0.700000,36.200000,24.300000,95.000000,57.000000,18.400000
max,14.790000,-4.300000,2022-12-31 00:00:00,175.000000,45.200000,32.500000,100.000000,94.000000,37.100000
std,1.380310,5.181990,NaN,6.502772,3.496509,2.771681,26.489839,22.290633,4.075944

In [54]:
# description des données catégorielles
df2.describe(include=["str"])

        ville     pays
count   28488    28488
unique      6        3
top     Thiès  Sénégal
freq     4748    18992

In [55]:
# nombre de valeurs manquantes par colonne
df2.isnull().sum()

ville               0
pays                0
latitude            0
longitude           0
date                0
precipitation_mm    0
temp_max_c          0
temp_min_c          0
humidite_max_pct    0
humidite_min_pct    0
vent_max_kmh        0
dtype: int64

In [56]:
# nombre de valeurs manquantes globale
df2.isnull().sum().sum()

np.int64(0)

- Nombre de colonnes : 11
- Colonnes de type catégorielle : 2
- Colonnes de type numérique : 9
- Nombre de ligne : 28 488
- Période : 2010-2022 (données journalières)
- Pas de valeurs manquantes

## Conclusion

Nos deux fichiers contiennent des données semi structurées. Dans la suite de notre travail, nous allons les structurer sous format de table de BD et introduire les données dans le SGBD de notre choix. Les différents tables possibles sont...

In [ ]:
# Extraction des pays de l'Afrique de l'Ouest à partir de la colonne "country"
west_africa_countries = ['Benin', 'Burkina Faso', 'Cape Verde', 'Côte d\'Ivoire', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Mauritania', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo']